import 'package:biux/config/styles.dart';
import 'package:flutter/material.dart';

final ThemeData darkTheme = ThemeData(
  primarySwatch: MaterialColor(4280819525, {
    50: Color(0xfff0edf7),
    100: Color(0xffe0dcef),
    200: Color(0xffc2b9df),
    300: Color(0xffa395d0),
    400: Color(0xff8572c0),
    500: Color(0xff664fb0),
    600: Color(0xff523f8d),
    700: Color(0xff3d2f6a),
    800: Color(0xff292046),
    900: Color(0xff141023)
  }),
  brightness: Brightness.dark,
  primaryColor: Color(0xff281f45),
  //primaryColorBrightness: Brightness.dark,
  primaryColorLight: Color(0xff9e9e9e),
  primaryColorDark: Color(0xff000000),
  //accentColor: Color(0xff000047),
//  accentColorBrightness: Brightness.light,
  canvasColor: Color(0xff2e3a5c),
  scaffoldBackgroundColor: Color(0xff1E2947),
  //bottomAppBarColor: Color(0xff424242),
  cardColor: Color(0xff2e3b5a),
  dividerColor: Color(0x1fffffff),
  highlightColor: Color(0x40cccccc),
  splashColor: Color(0x40cccccc),
  //selectedRowColor: Color(0xfff5f5f5),
  unselectedWidgetColor: Color(0xb3ffffff),
  disabledColor: Color(0x62ffffff),
  //toggleableActiveColor: Color(0xff000082),
  secondaryHeaderColor: Color(0xff616161),
  //textSelectionColor: Color(0xff000034),
  //cursorColor: Color(0xff4285f4),
  //textSelectionHandleColor: Color(0xff000036),
  //backgroundColor: Color(0xff616161),
  dialogBackgroundColor: Color(0xff424242),
  indicatorColor: Color(0xff000050),
  hintColor: Color(0x80ffffff),
  //errorColor: Color(0xffd32f2f),
  buttonTheme: ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 32, right: 32),
    shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    alignedDropdown: false,
    buttonColor: Color(0xff2e3b5a),
    disabledColor: Color(0x61ffffff),
    highlightColor: Color(0x29ffffff),
    splashColor: Color(0x1fffffff),
    focusColor: Color(0x1fffffff),
    hoverColor: Color(0x0affffff),
    colorScheme: ColorScheme(
      primary: Color(0xff1e2848),
      //primaryVariant: Color(0xff000000),
      secondary: Color(0xff64ffda),
      //secondaryVariant: Color(0xff00bfa5),
      surface: Color(0xff424242),
      background: Color(0xff616161),
      error: Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xff000000),
      onSurface: Color(0xffffffff),
      onBackground: Color(0xffffffff),
      onError: Color(0xff000000),
      brightness: Brightness.dark,
    ),
  ),
  textTheme: TextTheme(
      //headline1: Styles.headline,
      //headline2: Styles.headline,
      //headline3: Styles.headline,
      //headline4: Styles.headline,
      //headline5: Styles.headline,
      //headline6: Styles.headline,
      //subtitle1: Styles.headline,
      //bodyText2: Styles.headline,
      //bodyText1: Styles.headline,
      //caption: Styles.headline,
      //button: Styles.headline,
      //subtitle2: Styles.headline,
      //overline: Styles.headline,
      ),
  primaryTextTheme: TextTheme(
      //headline1: Styles.headline,
      //headline2: Styles.headline,
      //headline3: Styles.headline,
      //headline4: Styles.headline,
      //headline5: Styles.headline,
      //headline6: Styles.headline,
      //subtitle1: Styles.headline,
      //bodyText1: Styles.headline,
      //bodyText2: Styles.headline,
      //caption: Styles.headline,
      //button: Styles.headline,
      //subtitle2: Styles.headline,
      //overline: Styles.headline,
      ),
  // accentTextTheme: TextTheme(
  //   headline1: Styles.headline,
  //   headline2: Styles.headline,
  //   headline3: Styles.headline,
  //   headline4: Styles.headline,
  //   subtitle2: Styles.headline,
  //   subtitle1: Styles.headline,
  //   bodyText2: Styles.headline,
  //   bodyText1: Styles.headline,
  //   caption: Styles.headline,
  //   button: Styles.headline,
  //   overline: Styles.headline,
  // ),
  inputDecorationTheme: InputDecorationTheme(
    labelStyle: Styles.headline,
    helperStyle: Styles.headline,
    hintStyle: Styles.headline,
    errorStyle: Styles.error,
    errorMaxLines: null,
    isDense: false,
    contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 0, right: 0),
    isCollapsed: false,
    prefixStyle: Styles.headline,
    suffixStyle: Styles.headline,
    counterStyle: Styles.headline,
    filled: true,
    fillColor: Color(0xff2e3b5a),
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    errorBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff4285f4),
        width: 3,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    focusedBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff000000),
        width: 2,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    focusedErrorBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff4285f4),
        width: 3,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    disabledBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff000000),
        width: 3,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    enabledBorder: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff000000),
        width: 3,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
    border: UnderlineInputBorder(
      borderSide: BorderSide(
        color: Color(0xff000000),
        width: 3,
        style: BorderStyle.solid,
      ),
      borderRadius: BorderRadius.all(Radius.circular(4.0)),
    ),
  ),
  iconTheme: IconThemeData(
    color: Color(0xffffffff),
    opacity: 1,
    size: 24,
  ),
  primaryIconTheme: IconThemeData(
    color: Color(0xffffffff),
    opacity: 1,
    size: 24,
  ),
  // accentIconTheme: IconThemeData(
  //   color: Color(0xff000000),
  //   opacity: 1,
  //   size: 24,
  // ),
);

final lightTheme = ThemeData(
  primarySwatch: MaterialColor(4280957571, {
    50: Color(0xffeceef9),
    100: Color(0xffd8ddf3),
    200: Color(0xffb2bbe6),
    300: Color(0xff8b99da),
    400: Color(0xff6577cd),
    500: Color(0xff3e55c1),
    600: Color(0xff32449a),
    700: Color(0xff253374),
    800: Color(0xff19224d),
    900: Color(0xff0c1127)
  }),
  primaryColor: Colors.white,
  brightness: Brightness.light,
  //backgroundColor: const Color(0xFFE53935),
  //accentColor: Colors.black,
  canvasColor: Colors.white,
  cardColor: Colors.white,
  //accentIconTheme: IconThemeData(color: Colors.white),
  dividerColor: Colors.white54,
);
