// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIHhit8FtV5PKzYs3ztI217tM8ttcR9I',
    appId: '1:1047544274797:ios:4c1d3b8991728be76dc464',
    messagingSenderId: '1047544274797',
    projectId: 'biux-1576614678644',
    databaseURL: 'https://biux-1576614678644-default-rtdb.firebaseio.com',
    storageBucket: 'biux-1576614678644.appspot.com',
    androidClientId:
        '1047544274797-6c44qs41vma258e6fbt4rnvm3i5uqjql.apps.googleusercontent.com',
    iosClientId:
        '1047544274797-kfd5pkg38smus0p9m6l81eq2lufq24ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.biux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRKxMumNd_R_j1eeKCmj4ZDK3YHZRm9c',
    appId: '1:1047544274797:web:c080e371872675a76dc464',
    messagingSenderId: '1047544274797',
    projectId: 'biux-1576614678644',
    authDomain: 'biux-1576614678644.firebaseapp.com',
    databaseURL: 'https://biux-1576614678644-default-rtdb.firebaseio.com',
    storageBucket: 'biux-1576614678644.appspot.com',
    measurementId: 'G-HPQ98V1426',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRKxMumNd_R_j1eeKCmj4ZDK3YHZRm9c',
    appId: '1:1047544274797:web:c080e371872675a76dc464',
    messagingSenderId: '1047544274797',
    projectId: 'biux-1576614678644',
    authDomain: 'biux-1576614678644.firebaseapp.com',
    databaseURL: 'https://biux-1576614678644-default-rtdb.firebaseio.com',
    storageBucket: 'biux-1576614678644.appspot.com',
    measurementId: 'G-HPQ98V1426',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIHhit8FtV5PKzYs3ztI217tM8ttcR9I',
    appId: '1:1047544274797:ios:2f33fcae8fbaeb5f6dc464',
    messagingSenderId: '1047544274797',
    projectId: 'biux-1576614678644',
    databaseURL: 'https://biux-1576614678644-default-rtdb.firebaseio.com',
    storageBucket: 'biux-1576614678644.appspot.com',
    androidClientId:
        '1047544274797-6c44qs41vma258e6fbt4rnvm3i5uqjql.apps.googleusercontent.com',
    iosClientId:
        '1047544274797-bk26jufigkthtcea5rht0mq1d5nv8vca.apps.googleusercontent.com',
    iosBundleId: 'com.example.biux2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo-m8HwLX29RWt-24qItFMtskNCb6ahjE',
    appId: '1:1047544274797:android:e33e776147e7458b6dc464',
    messagingSenderId: '1047544274797',
    projectId: 'biux-1576614678644',
    databaseURL: 'https://biux-1576614678644-default-rtdb.firebaseio.com',
    storageBucket: 'biux-1576614678644.appspot.com',
  );
}
